schema:
  - name: Web Site
    path: cmd/web_server
    commands:
      install:
        status: true
      run:
        status: true
      build:
        status: false
    watcher:
      paths:
        - ../../
      extensions:
        - go
      ignored_paths:
        - .git
        - node_modules
        - vendor
        - assets
  - name: Consumer
    path: cmd/consumers
    commands:
      install:
        status: true
      run:
        status: true
      build:
        status: false
    watcher:
      paths:
        - ../../
      extensions:
        - go
      ignored_paths:
        - .git
        - node_modules
        - vendor
        - assets
  - name: Chat Bot
    path: cmd/chat_bot
    commands:
      install:
        status: true
      run:
        status: true
      build:
        status: false
    watcher:
      preview: true
      paths:
        - ../../
      extensions:
        - go
      ignored_paths:
        - .git
        - node_modules
        - vendor
        - assets
  - name: CronJobs
    path: cmd/crons
    commands:
      install:
        status: true
      run:
        status: true
      build:
        status: false
    watcher:
      preview: true
      paths:
        - ../../
      extensions:
        - go
      ignored_paths:
        - .git
        - node_modules
        - vendor
        - assets
