ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 0
warningCode = 0

#[rule.add-constant]
#[rule.argument-limit]
[rule.atomic]
[rule.blank-imports]
[rule.bool-literal-in-expr]
[rule.call-to-gc]
#[rule.confusing-naming]
[rule.confusing-results]
[rule.constant-logical-expr]
[rule.context-as-argument]
[rule.context-keys-type]
#[rule.cyclomatic]
[rule.deep-exit]
[rule.dot-imports]
[rule.empty-block]
#[rule.empty-lines]
[rule.error-naming]
[rule.error-return]
[rule.error-strings]
[rule.errorf]
#[rule.exported]
#[rule.file-header]
[rule.flag-parameter]
#[rule.function-result-limit]
[rule.get-return]
[rule.if-return]
[rule.imports-blacklist]
[rule.increment-decrement]
[rule.indent-error-flow]
#[rule.line-length-limit]
#[rule.max-public-structs]
[rule.modifies-parameter]
[rule.modifies-value-receiver]
[rule.package-comments]
[rule.range-val-in-closure]
[rule.range]
[rule.receiver-naming]
[rule.redefines-builtin-id]
[rule.struct-tag]
[rule.superfluous-else]
[rule.time-naming]
[rule.unexported-return]
[rule.unnecessary-stmt]
[rule.unreachable-code]
#[rule.unused-parameter]
#[rule.var-declaration]
#[rule.var-naming]
[rule.waitgroup-by-value]
